title: Miklin Mikhail
description: Python, C++, JS programmer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

logo: https://avatars1.githubusercontent.com/u/37439522

github_username:  MiklinMA
facebook_username: MiklinMA
instagram_username: MiklinMA
linkedin_username: MiklinMA
googleplus_username: +MiklinMA
